### ISSUE TITLE
Error 20 even with basic Gcode

### ISSUE THREAD

**Issue by Cncninja** [terjeio/ioSender#129]
I keep getting an error 20 when trying to run a program. it runs fine in other senders and I'm using the Grbl PP in fusion 360
![ice_screenshot_20210910-233942](https://user-images.githubusercontent.com/75448047/132939139-7a40bea2-c70d-44a8-98d3-e22da90bbcf9.jpeg)
any idea what could cause this?

**Comment by terjeio** [comment]
> any idea what could cause this?

It is because line 17 is invalid in grblHAL when tool table support is not enabled. [G43H1](http://www.linuxcnc.org/docs/2.6/html/gcode/gcode.html#sec:G43) sets tool length offset for tool 1, the controller cannot execute that unless a tool table is present. Perhaps the other senders you have tried implements a tool table locally or strips G43 commands?
