### ISSUE TITLE
Keyboard jogging does not seem to use grblHAL settings ($50-55)

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/ioSender#177]
This is with the  T4.1 port and ioSender 2.0.35 (and various recent edge versions).

It looks like step jogging (ctrl+cursor) is always .1 mm no matter what $53 is set to.  I tried setting slow jog rate and distance to crazy number ($51=6000, $54=5000) and still get fairly short/slow movement.  Perhaps I am doing something wrong?

[edit] Ah, it looks like the jog panel setting is used for step jog.  The wiki needs updating.

**Comment by Bert911** [comment]
I'm not seeing any of the setting ($50-55) with the new Iosender 2.0.36 but like the new XL interface very much.

I'm using also the T4.1 with Ethernet and using Phil's prebuilt version from the 03.01.2022.
It's no big trouble but it would be nice to have jogging above 500 mm/min again.

Manually changing $51 any setting ($50-55) result in an error:

error:53 - Setting is not available, possibly due to limited driver support.

**Comment by terjeio** [comment]
Settings `$50-55` is only available if the keypad plugin is compiled in, if not keyboard jogging feedrates are set in the _Settings: App_ tab.
New is that continuous keyboard jogging has been disabled due to user requests - by default keyboard jogging uses parameters from the UI jog panel, in the same way that most other sender does. This can be overridden by creating a shortcut to the executable and [adding a command line parameter](https://github.com/terjeio/ioSender/wiki/Setup-and-configuration) (`-jogmode`) to select which type of jogging to use.

**Comment by Bert911** [comment]
I'm feeling like you're trolling me  :grin:

The settings from the UI Jogging differs from my keyboard jogging.
Keyboard Jogging uses 200 mm/min, 500 with "shift" and 100 with "ctrl".

In the _Settings: App_ tab I don't have these settings any more, but I know this settings from the older versions of Iosender.

What am I missing?

![UI_1](https://user-images.githubusercontent.com/94561142/151662885-7511b99b-2834-4dc5-a361-9bc56d5e9445.PNG)

**Comment by terjeio** [comment]
> The settings from the UI Jogging differs from my keyboard jogging.
Keyboard Jogging uses 200 mm/min, 500 with "shift" and 100 with "ctrl".

A bug?, I'll have to check that.

With these shortcut parameters:

![image](https://user-images.githubusercontent.com/20260062/151663605-0d470537-e8b4-4a9a-aa1e-984e5b68b20b.png)

I get:

![image](https://user-images.githubusercontent.com/20260062/151663657-8f78bcd5-ab8f-4e1a-860e-afb812d00b94.png)

And with `-jogmode 2` I get both the _UI jogging_ and _Keyboard jogging_ panels.

**Comment by Bert911** [comment]
I may have missed the "1" in -jogmode 1.
With `-jogmode 2` I get the known settings, but they don't work :neutral_face:

**Comment by terjeio** [comment]
Can you try the [latest edge version](http://www.io-engineering.com/downloads)? There was a bit of code missing in the XL build.

**Comment by Bert911** [comment]
Works like a charm with the new version.

Thank you very much!

**Comment by prcdslnc13** [comment]
I am getting the same issue with the latest edge builds and 2.0.42. No keyboard Jogging pane with -jogmode 2 in the parameters. 
![image](https://github.com/terjeio/ioSender/assets/4261337/b2fc8425-2d47-4336-9cd6-0654eaefabe0)

![image](https://github.com/terjeio/ioSender/assets/4261337/18616b65-cfe3-4117-96ce-944c1031e679)

It's not working with the XL or normal version.

**Comment by terjeio** [comment]
@prcdslnc13 Do you have the keypad plugin active in the controller? If so the keyboard jog settings are found in the _Settings: Grbl_ tab and inherited from there.

**Comment by prcdslnc13** [comment]
Oh interesting. I do have keypad active. Ill try that. Thank you!

**Comment by prcdslnc13** [comment]
Ok what I found was the Keypad settings were not respected but I was able to change the speed in the app.config file here 
![image](https://github.com/terjeio/ioSender/assets/4261337/69a5297a-490d-457e-9dba-ec2050bec56c)
