### ISSUE TITLE
Alpha 17 feedback

### ISSUE THREAD

**Issue by phil-barrett** [terjeio/ioSender#24]
Downloaded and ran A17 for a while. Haven't pushed it very hard but here are my initial thoughts.

Overall, polish and features have clearly matured. Looks good! You still want to call it Alpha level quality? I think it's ready for broader use. But, of course, that's your call.

Some thoughts on A17:
- I like the Open/Reload/edit/close menu. Edit is a very helpful feature. Is the editor choice configurable? I have not played with these features enough to give in depth feedback.  A minor nit on the word reload - you open a file but then reload it. Seems a little inconsistent - Open and Reopen or Load and Reload are more consistent in my mind. Regardless of the name, I like the feature as I often reload (lol) a file and that saves going through the file open process.  Since edit triggers an external editor, perhaps load/reload is a better choice.
- Thank you for App max and min!
- I haven't tested the probing tab but have started looking into it.  Will have more (mostly questions, I think) later. It looks pretty substantial.
- Camera Tab.  How does move offset work?  It doesn't seem to do anything that I could see.
- Camera Tab. (more of an unrelated question) How would I monitor my CNC remotely? Is there a way for TSender to act as a server? Or at least coordinating the connection? I suppose it's better to set up a separate system and not add that to TSender.
- Repeating myself here but it would be good to be able to change Com port and related settings via a menu item (and without app restart).
- I have not tested it against legacy grbl systems but the features you have added make it stand well above the other senders out there.  It might be worth some effort - all us grbl panel refugees need something better than bCNC and UGS.
- Start, hold and stop buttons - this is a personal preference issue but I would like to see the standard start, pause and stop icons. Instantly recognizable for what they are. I'd use mouse hover-hint text to show the keyboard alternatives.

In the next week or so, I will be converting my router over to use grblHAL and TSender so will have more feedback.

And again, TSender is really nice.  Well done!

**Comment by terjeio** [comment]
* Alpha status: I am perhaps a bit conservative regarding this, this since I know there is still a lot of work to do before I am comfortable to mark it as production ready. However, compared to some of the senders I have used for comparison and testing against grblHAL it is definitely not in alpha state... Anyway, I think more user feedback is required before I change the status.

* Open vs Load: _File > Open_ is a common standard so it has to be Reopen then...

* Edit: The Edit function will automatically reopen/reload the program when the editor exits if the file was changed. The editor is configurable, but not yet from the UI - currently you have to edit the App.config file to change it. On todo list, reason not yet added has to do with reopen/reload on editor exit and editors supporting multiple files open in tabs. E.g. Notepad++ which I use.

* Camera move offset: A offset has to be set in _Settings: App_ first. [Here](https://www.youtube.com/watch?v=AP8oFqAPOLI) is a YouTube video showing how it is done with Mach3. Short version: drill a small hole and set zero, move the spindle till the camera is centered on the hole, select _Settings: App_, click _Get current position_ in the Camera box and save settings. Then there is the issue of adjusting the camera to be paralell to the Z-axis...

* Remote camera: IMO not going to be a part of the sender, camera functionality is intended for optical probing and measurements - not for job monitoring.

* Com port selection: still chicken/egg situation as the sender configures itself from info retrieved from the grbl firmware. Slowly getting towards this beeing possible, the first step done by changing the app config class to a singleton... Not on top of my todo list I have to admit.

* Start, hold and stop buttons: I do not like the icons many uses... Pause = feed hold? Note that _Stop_ behaves differently with grblHAL and legacy grbl. grblHAL: immediately halts execution and rewinds program, position may be lost (done by a soft reset - I have added a new real-time command for that). grbl: stops sending - motion continues until buffer is exhausted. IMO bad if agressive buffering is enabled, maybe why most senders avoid using that?.

Tsender is aimed at similar users as those who would use/uses [Grbl-Panel](https://github.com/gerritv/Grbl-Panel), ref a quote from the grbl wiki about Grbl-Panel:

> ...a GUI that implements more advanced features and functionality commonly found in production machines...

Many thanks for the feedback.
