### ISSUE TITLE
Cartesian and Build Environment

### ISSUE THREAD

**Issue by silver2row** [terjeio/ioSender#343]
Hello,

I have been learning about iosender w/ my current board. grblHAL breakout board is the board in question...

Anyway, outside of the board, I am trying to get my cartesian laser set up. I am having issues. 

First off, part of it is me. My 18" * 18" build environment on the cartesian needs a new set up. The end stop needs to be situated a bit better. So, I can hand click the end stop to handle zeroing the machine for builds...

1. Is there a way to set the size of the machine build environment?
2. This seems like it is needed.
3. I have not found the correct parameters for setting the cartesian build envelope which is 18" * 18" or roughly 458mm * 458mm.

Seth

P.S. I found the side menu options of iosender. It acts like it will scroll the XY outer perimeter of the build piece but w/out my cartesian 458mm * 458mm, I am sort of lost. Also...

This error: `feed rate has not been set or is undefined` keeps coming up when trying to maneuver around the build environment.

**Comment by silver2row** [comment]
Hello...thank you. So, when I set `$130 X458` and `$131 Y458`, it sets my boundaries of how far I can travel...okay.

Also, I need to set Feed Rate at some interval. Okay. `F500` will accomplish this idea. Okay...

I cut out homing for now b/c of my location issues on the cartesian plane. It seems my Y_Axis keeps stopping short of the homing end stop switch which is the min switch. The X_Axis min end stop works but b/c the Y_Axis end stop stops prematurely, the X_Axis never homes, i.e. hence me cutting out homing for now.

Seth

P.S. What is a normal feed rate for a cheap machine? I have good drivers but my motors are silly and my machine motors can handle the frame easily. The frame is cheap. I have been working w/ this cheap machine to get better acquainted w/ grblHAL and iosender for use on Windows 11 machines.

**Comment by silver2row** [comment]
Also sir,

I do this...

```
1. $130 X458
2. $131 Y458
3. G0 Y25 F25
```

After number 3. has been applied, the machine goes on forever and not just 25mm at a feed rate of 25.

Is this due to not having homing set up and the limit switches being set up?

Seth

**Comment by silver2row** [comment]
# Update

I read one of your articles on your website, sir. Nice! Imperial was used on the software for CAD/CAM while the iosender source used metric. Blah. Okay. I will figure this out. Sorry for harassing you.

Seth

**Comment by terjeio** [comment]
> P.S. What is a normal feed rate for a cheap machine?

Impossible to tell, acceleration plays a role as well the hardness of the material you want to cut, depth of cut and the size of the tool... If not cutting you may try increasing the both the max feed rate and the acceleration until the motor stalls and back off from the values where stalling occurs. 

> Is this due to not having homing set up and the limit switches being set up?

Not really. G0Y25 commands movement to the _absolute_ position 25mm, how large the actual movement will be depends on the position the movement starts from. If the starting position is not 0 it can be smaller or larger.

Have you [calibrated your axes](https://duckduckgo.com/?t=ffab&q=grbl+calibrate+motors&ia=web) so that steps/mm matches the machine? Most steppers produces one turn per 200 steps. E.g. if you have stepper drivers set to 8 microsteps and a screw that produces 2mm movement per turn then the steps/mm setting should be 200 * 8 / 2 = 800 steps/mm. If the machine is belt driven the math is a [bit more complicated](https://zalophusdokdo.github.io/StepperMotorsCalculator/en/index.html).

**Comment by phil-barrett** [comment]
[This might help](https://www.grbl.org/single-post/calibrating-grblhal-cnc-system-movement) you calibrating.  You don't even need to work through the gearing for your belts - just use your initial guess and adjust from there.

**Comment by silver2row** [comment]
Okay...thank you guys/gals. I appreciate the assistance in this endeavor. I will go to the grbl site and review things.

**Comment by silver2row** [comment]
So, is it $100 X400 and not $130 X400 for stating the maximum travel the X_Axis will handle on my machine?

I see your post here but then read and reread the blog you referenced. Each seem to be different...

Seth

**Comment by phil-barrett** [comment]
FWIW, you send
`$130=400`
to Grbl via MDI in your GCode sender.

**Comment by silver2row** [comment]
Right. Okay, I was misreading what was typed out. You are right.
