### ISSUE TITLE
Can you add and cancel the grid and change the color of the grid?

### ISSUE THREAD

**Issue by lianzaozi** [terjeio/ioSender#74]
Can you add and cancel the grid and change the color of the grid?

As shown in the figure below: the track display color is the same as the grid display color. The grid blocks the track, which makes it hard for me to see.

![Snipaste_2020-12-05_16-16-56](https://user-images.githubusercontent.com/53146195/101237679-b4acda80-3715-11eb-8827-258c97ad9592.png)

**Comment by lianzaozi** [comment]
I know that the candle software allows me to change the color of the display, and allows me to decide what to display/not to display.

Candle software screenshot
![image](https://user-images.githubusercontent.com/53146195/101237780-6815cf00-3716-11eb-97fb-3d50ad761f83.png)

**Comment by terjeio** [comment]
The 3D-viewer will get more [attention later](https://github.com/terjeio/Grbl-GCode-Sender/wiki/Roadmap) when the first production release is out, this can be a part of that. Thanks for the feedback.

**Comment by terjeio** [comment]
Took some time to get to the first production release... I have now played a bit with the viewer, added color selection and made the first attempt at highlighting path to be executed (a bit ahead of the "tool" due to the planner buffer in the controller).

![image](https://user-images.githubusercontent.com/20260062/118368207-1feeb880-b5a2-11eb-9463-59723a38a1b1.png)

The changes can be tested by downloading the latest edge version (33p5) [from here](http://www.io-engineering.com/downloads).
