### ISSUE TITLE
GUI don't catch M5 command

### ISSUE THREAD

**Issue by calabr** [terjeio/ioSender#86]
Sender Beta-8.8
GRBL 1.1h
  GUI correctly show M3, M4 and Sxxx commands from MDI or file, but ignore M5 and S0.
  Spindle state updated after M8 command.
to reproduce send from MDI
1:
M3S1000
M5
  Spindle indicator still show CW 1000
console responce 
<Idle|MPos:-115.698,-98.815,-36.000|Bf:15,128|FS:0,0>
2:
  M3S1000
  M5
 Spindle indicator still show CW 1000
 M8
 Spindle indicator show "off"
3:
  M3S1000
  M8
  M5
Spindle and coolant follow the real state.

  WSO system in work parameters window also not follow current real state.

**Comment by terjeio** [comment]
This is a bug in the controller, it does not send back information in the `|A` element in the real-time report when the spindle is turned off. IIRC an issue has already been raised about this but it has not yet been fixed. Note that if coolant it active then it is sent and detected.

Same goes for the G5x offsets, changes are not reported back when they happens.

Both these bugs are fixed in [grblHAL](https://github.com/terjeio/grblHAL).

**Comment by calabr** [comment]
According to current situation with messages,  
I propose to revert back Betta 8 behaviour and add additional popup window,  for example on the click to status indicator or behind it,  with short event log,  for example 
Time,  event,  description (helpful for alarms and errors)  
For 2-3 latest events.  
Only events,  which changing state indication. 
Looking console can be confusing for some users,  especially traffic - saving communication shortening in GRBL

**Comment by terjeio** [comment]
I have managed to create a workaround for M5 by using spindle speed = 0 from the `Fs:` element. I will be a little while before I update as I am currently working on Trinamic driver interface and tuning.

**Comment by terjeio** [comment]
Workaround added to latest release.
